# Generated by Django 3.2.4 on 2021-06-25 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(related_name='followed_by', to='auctions.Listing')),
                ('user', models.ManyToManyField(related_name='watch_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
