# Generated by Django 3.2.4 on 2021-06-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210625_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
