# Generated by Django 3.2.4 on 2021-06-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='unique_watch'),
        ),
    ]
