# Generated by Django 3.2.4 on 2021-06-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210625_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.IntegerField(choices=[(0, 'Close'), (1, 'Open')], default=1),
        ),
    ]
