# Generated by Django 3.2.4 on 2021-06-28 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
        migrations.CreateModel(
            name='CloseBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won', to='auctions.bid')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closed', to='auctions.listing')),
            ],
        ),
    ]
