# Generated by Django 3.2.4 on 2021-06-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210628_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Plant'), (3, 'Harry'), (4, 'Book')], null=True),
        ),
    ]
