# Generated by Django 3.2.4 on 2021-07-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='url',
        ),
        migrations.AddField(
            model_name='listing',
            name='picture',
            field=models.ImageField(default='plant.jpeg', upload_to='listing_pics'),
        ),
    ]
