# Generated by Django 3.2.4 on 2021-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='picture',
        ),
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
